In [6]:
import pandas as pd
import numpy as np
import warnings

In [7]:
df = pd.read_csv("C:/Users/Omkar Kurane/Downloads/bondora_analysis.csv",low_memory=False)

In [8]:
df.head(2)

,Loan_Id,LoanNumber,LoanDate,ContractEndDate,FirstPaymentDate,Age,Gender,Country,AppliedAmount,Amount,...,DebtToIncome,ExpectedLoss,ExpectedReturn,ProbabilityOfDefault,DefaultDate,Rating,Status,PrincipalPaymentsMade,InterestAndPenaltyPaymentsMade,PrincipalBalance
0,66AE108B-532B-4BB3-BAB7-0019A46412C1,483449,23-03-2016,26-06-2020,12-05-2016,53,1.0,EE,2125.0,2125.0,...,26.29,0.0685,0.141145,0.122216,14-01-2020,C,Late,969.16,1187.91,1155.84
1,D152382E-A50D-46ED-8FF2-0053E0C86A70,378148,25-06-2015,NaN,17-08-2015,50,1.0,EE,3000.0,3000.0,...,30.58,0.0308,0.140436,0.036400,02-06-2016,B,Late,563.59,360.07,2436.41

In [9]:
df.shape

(179235, 27)

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 179235 entries, 0 to 179234
Data columns (total 27 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   Loan_Id                         179235 non-null  object
 1   LoanNumber                      179235 non-null  int64
 2   LoanDate                        179235 non-null  object
 3   ContractEndDate                 102996 non-null  object
 4   FirstPaymentDate                179235 non-null  object
 5   Age                             179235 non-null  int64
 6   Gender                          179190 non-null  float64
 7   Country                         179235 non-null  object
 8   AppliedAmount                   179235 non-null  float64
 9   Amount                          179235 non-null  float64
 10  Interest                        179235 non-null  float64
 11  LoanDuration                    179235 non-null  int64
 12  MonthlyPayment                  172545 non-null  float64
 13  Education                       179185 non-null  float64
 14  EmploymentStatus                179033 non-null  float64
 15  OccupationArea                  179144 non-null  float64
 16  IncomeTotal                     179235 non-null  float64
 17  DebtToIncome                    179185 non-null  float64
 18  ExpectedLoss                    176596 non-null  float64
 19  ExpectedReturn                  176596 non-null  float64
 20  ProbabilityOfDefault            176596 non-null  float64
 21  DefaultDate                     71416 non-null   object
 22  Rating                          176502 non-null  object
 23  Status                          179235 non-null  object
 24  PrincipalPaymentsMade           179235 non-null  float64
 25  InterestAndPenaltyPaymentsMade  179235 non-null  float64
 26  PrincipalBalance                179235 non-null  float64
dtypes: float64(16), int64(3), object(8)
memory usage: 36.9+ MB

In [11]:
df.describe(include='all')

,Loan_Id,LoanNumber,LoanDate,ContractEndDate,FirstPaymentDate,Age,Gender,Country,AppliedAmount,Amount,...,DebtToIncome,ExpectedLoss,ExpectedReturn,ProbabilityOfDefault,DefaultDate,Rating,Status,PrincipalPaymentsMade,InterestAndPenaltyPaymentsMade,PrincipalBalance
count,179235,1.792350e+05,179235,102996,179235,179235.000000,179190.000000,179235,179235.000000,179235.000000,...,179185.000000,176596.000000,176596.000000,176596.000000,71416,176502,179235,179235.000000,179235.000000,179235.000000
unique,179235,NaN,4041,4670,2477,NaN,NaN,4,NaN,NaN,...,NaN,NaN,NaN,NaN,1943,8,3,NaN,NaN,NaN
top,65C924CD-8AAF-4ECC-9C8F-FFB0C5722CBB,NaN,15-10-2019,27-04-2026,04-11-2019,NaN,NaN,EE,NaN,NaN,...,NaN,NaN,NaN,NaN,23-12-2019,D,Late,NaN,NaN,NaN
freq,1,NaN,455,573,2030,NaN,NaN,110714,NaN,NaN,...,NaN,NaN,NaN,NaN,569,36784,68574,NaN,NaN,NaN
mean,NaN,1.239306e+06,NaN,NaN,NaN,40.389137,0.466801,NaN,2699.127966,2543.473023,...,5.830897,0.135989,0.130520,0.232322,NaN,NaN,NaN,972.594732,599.097238,1544.159037
std,NaN,6.610266e+05,NaN,NaN,NaN,12.359547,0.620359,NaN,2342.758228,2182.064156,...,14.481862,0.108723,0.067655,0.140570,NaN,NaN,NaN,1474.338194,957.071691,1937.975362
min,NaN,3.700000e+01,NaN,NaN,NaN,0.000000,0.000000,NaN,10.000000,6.390000,...,0.000000,0.000000,-0.798891,0.000000,NaN,NaN,NaN,0.000000,0.000000,-34.200000
25%,NaN,7.125380e+05,NaN,NaN,NaN,31.000000,0.000000,NaN,740.000000,740.000000,...,0.000000,0.061200,0.100230,0.124240,NaN,NaN,NaN,110.420000,68.750000,0.000000
50%,NaN,1.096557e+06,NaN,NaN,NaN,39.000000,0.000000,NaN,2125.000000,2125.000000,...,0.000000,0.111695,0.128022,0.209589,NaN,NaN,NaN,426.850000,246.140000,716.040000
75%,NaN,1.851458e+06,NaN,NaN,NaN,49.000000,1.000000,NaN,4150.000000,3825.000000,...,0.000000,0.165935,0.151564,0.319356,NaN,NaN,NaN,1156.345000,740.345000,2285.675000
max,NaN,2.313298e+06,NaN,NaN,NaN,77.000000,2.000000,NaN,10632.000000,10632.000000,...,198.020000,1.008540,0.808546,0.994429,NaN,NaN,NaN,10632.000000,18393.460000,10632.000000

In [12]:
df.isnull().sum().sort_values(ascending=False)

DefaultDate                       107819
ContractEndDate                    76239
MonthlyPayment                      6690
Rating                              2733
ExpectedLoss                        2639
ProbabilityOfDefault                2639
ExpectedReturn                      2639
EmploymentStatus                     202
OccupationArea                        91
DebtToIncome                          50
Education                             50
Gender                                45
Interest                               0
AppliedAmount                          0
Country                                0
Age                                    0
FirstPaymentDate                       0
LoanNumber                             0
LoanDate                               0
Loan_Id                                0
Amount                                 0
IncomeTotal                            0
LoanDuration                           0
Status                                 0
PrincipalPaymentsMade                  0
InterestAndPenaltyPaymentsMade         0
PrincipalBalance                       0
dtype: int64

In [13]:
df.duplicated().sum()

np.int64(0)

In [14]:
df.dtypes

Loan_Id                            object
LoanNumber                          int64
LoanDate                           object
ContractEndDate                    object
FirstPaymentDate                   object
Age                                 int64
Gender                            float64
Country                            object
AppliedAmount                     float64
Amount                            float64
Interest                          float64
LoanDuration                        int64
MonthlyPayment                    float64
Education                         float64
EmploymentStatus                  float64
OccupationArea                    float64
IncomeTotal                       float64
DebtToIncome                      float64
ExpectedLoss                      float64
ExpectedReturn                    float64
ProbabilityOfDefault              float64
DefaultDate                        object
Rating                             object
Status                             object
PrincipalPaymentsMade             float64
InterestAndPenaltyPaymentsMade    float64
PrincipalBalance                  float64
dtype: object

In [15]:
date_columns = ['LoanDate','ContractEndDate','FirstPaymentDate','DefaultDate']
for i in date_columns:
    df[i]=pd.to_datetime(df[i],errors='coerce')

C:\Users\Omkar Kurane\AppData\Local\Temp\ipykernel_33892\239028356.py:3: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[i]=pd.to_datetime(df[i],errors='coerce')
C:\Users\Omkar Kurane\AppData\Local\Temp\ipykernel_33892\239028356.py:3: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[i]=pd.to_datetime(df[i],errors='coerce')
C:\Users\Omkar Kurane\AppData\Local\Temp\ipykernel_33892\239028356.py:3: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[i]=pd.to_datetime(df[i],errors='coerce')

In [16]:
df.dtypes

Loan_Id                                   object
LoanNumber                                 int64
LoanDate                          datetime64[ns]
ContractEndDate                   datetime64[ns]
FirstPaymentDate                  datetime64[ns]
Age                                        int64
Gender                                   float64
Country                                   object
AppliedAmount                            float64
Amount                                   float64
Interest                                 float64
LoanDuration                               int64
MonthlyPayment                           float64
Education                                float64
EmploymentStatus                         float64
OccupationArea                           float64
IncomeTotal                              float64
DebtToIncome                             float64
ExpectedLoss                             float64
ExpectedReturn                           float64
ProbabilityOfDefault                     float64
DefaultDate                       datetime64[ns]
Rating                                    object
Status                                    object
PrincipalPaymentsMade                    float64
InterestAndPenaltyPaymentsMade           float64
PrincipalBalance                         float64
dtype: object

In [17]:
numeric_columns = ['MonthlyPayment','ExpectedLoss','ExpectedReturn','ProbabilityOfDefault','DebtToIncome']
for i in numeric_columns:
    df[i].fillna(df[i].median(),inplace=True)

C:\Users\Omkar Kurane\AppData\Local\Temp\ipykernel_33892\4152212301.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[i].fillna(df[i].median(),inplace=True)

In [19]:
categorical_columns = ['Gender','Education','EmploymentStatus','OccupationArea']
for i in categorical_columns:
    df[i].fillna(df[i].mode()[0],inplace=True)

C:\Users\Omkar Kurane\AppData\Local\Temp\ipykernel_33892\3432815017.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[i].fillna(df[i].mode()[0],inplace=True)

In [21]:
df['Rating'] = df['Rating'].fillna('Unkown')

In [22]:
df.isnull().sum().sort_values(ascending=False)

DefaultDate                       107819
FirstPaymentDate                   78791
ContractEndDate                    76239
LoanDate                               0
LoanNumber                             0
Age                                    0
Gender                                 0
Country                                0
AppliedAmount                          0
Amount                                 0
Loan_Id                                0
Interest                               0
LoanDuration                           0
Education                              0
MonthlyPayment                         0
OccupationArea                         0
IncomeTotal                            0
DebtToIncome                           0
EmploymentStatus                       0
ExpectedLoss                           0
ExpectedReturn                         0
ProbabilityOfDefault                   0
Rating                                 0
Status                                 0
PrincipalPaymentsMade                  0
InterestAndPenaltyPaymentsMade         0
PrincipalBalance                       0
dtype: int64

In [23]:
df['DefaultFlag'] = df["DefaultDate"].notna().astype(int)

In [24]:
df['OutstandingAmount'] = df['Amount'] - df['PrincipalPaymentsMade']

In [25]:
df['RepaymentPercentage'] = (df['PrincipalPaymentsMade']/df['Amount'])*100

In [26]:
df['TotalRecived'] = (df['PrincipalPaymentsMade']+df['InterestAndPenaltyPaymentsMade'])

In [28]:
Today = pd.Timestamp.today()
df['LoanAgeDays'] = (Today-df['LoanDate']).dt.days

In [39]:
df["RiskCategory"] = pd.cut(
    df["ProbabilityOfDefault"],
    bins=[0, 0.20, 0.40, 1],
    labels=["Low", "Medium", "High"],
    include_lowest=True
)

In [31]:
df["NetROI"] = (
    df["ExpectedReturn"] -
    df["ExpectedLoss"]
)

In [33]:
df['RepaymentPercentage'].describe()

count    179235.000000
mean         42.057313
std          39.549209
min           0.000000
25%           6.411276
50%          25.393227
75%          99.034569
max         107.644173
Name: RepaymentPercentage, dtype: float64

In [34]:
df["OutstandingAmount"].describe()

count    179235.000000
mean       1570.878292
std        1929.600168
min         -34.200000
25%          11.785000
50%         775.620000
75%        2305.490000
max       10632.000000
Name: OutstandingAmount, dtype: float64

In [35]:
df["NetROI"].describe()

count    179235.000000
mean         -0.005148
std           0.114596
min          -1.797781
25%          -0.022500
50%           0.014506
75%           0.047057
max           0.435923
Name: NetROI, dtype: float64

In [38]:
df["ProbabilityOfDefault"].describe()

count    179235.000000
mean          0.231987
std           0.139558
min           0.000000
25%           0.124240
50%           0.209589
75%           0.318264
max           0.994429
Name: ProbabilityOfDefault, dtype: float64

In [40]:
df['RiskCategory'].describe()

count     179235
unique         3
top          Low
freq       83981
Name: RiskCategory, dtype: object

In [41]:
df['RiskCategory'].value_counts()

RiskCategory
Low       83981
Medium    79015
High      16239
Name: count, dtype: int64

In [43]:
df.shape

(179235, 34)

In [44]:
df.to_csv("bondora_cleaned.csv", index=False)

In [45]:
df['NetROI'].isnull().sum()

np.int64(0)

In [46]:
df.isnull().sum()[df.isnull().sum() > 0]

ContractEndDate      76239
FirstPaymentDate     78791
DefaultDate         107819
dtype: int64

In [47]:
import pyodbc

In [48]:
import sqlalchemy

In [49]:
!pip install pyodbc sqlalchemy

Requirement already satisfied: pyodbc in c:\python\lib\site-packages (5.2.0)
Requirement already satisfied: sqlalchemy in c:\python\lib\site-packages (2.0.39)
Requirement already satisfied: greenlet!=0.4.17 in c:\python\lib\site-packages (from sqlalchemy) (3.1.1)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\python\lib\site-packages (from sqlalchemy) (4.12.2)

In [52]:
import pandas as pd

df = pd.read_csv(r"C:\Users\Omkar Kurane\OneDrive\Data_Analytics\Bondara_Project\bondora_cleaned.csv")

df.head()

,Loan_Id,LoanNumber,LoanDate,ContractEndDate,FirstPaymentDate,Age,Gender,Country,AppliedAmount,Amount,...,PrincipalPaymentsMade,InterestAndPenaltyPaymentsMade,PrincipalBalance,DefaultFlag,OutstandingAmount,RepaymentPercentage,TotalRecived,LoanAgeDays,NetROI,RiskCategory
0,66AE108B-532B-4BB3-BAB7-0019A46412C1,483449,23-03-2016,26-06-2020,05-12-2016,53,1,EE,2125.0,2125.0,...,969.16,1187.91,1155.84,1,1155.84,45.607529,2157.07,3786,0.072645,Low
1,D152382E-A50D-46ED-8FF2-0053E0C86A70,378148,25-06-2015,NaN,NaN,50,1,EE,3000.0,3000.0,...,563.59,360.07,2436.41,1,2436.41,18.786333,923.66,4058,0.109636,Low
2,87342E13-66CB-483F-833A-007953E50C78,451831,19-01-2016,24-10-2019,NaN,44,0,EE,10630.0,9100.0,...,6537.00,1708.47,0.00,1,2563.00,71.835165,8245.47,3850,0.090307,Low
3,87227056-6BF9-410C-98D1-008F788E122A,349381,27-03-2015,NaN,05-04-2015,42,0,ES,1500.0,1500.0,...,464.73,355.92,1035.27,1,1035.27,30.982000,820.65,4148,-0.037580,Low
4,2DDE6336-E466-4624-A337-00A0ED1A1468,443082,22-12-2015,NaN,02-01-2016,34,1,ES,1595.0,1090.0,...,0.01,0.00,1089.99,1,1089.99,0.000917,0.01,3878,-0.453438,High

In [53]:
df.isnull().sum().sort_values(ascending=False)

DefaultDate                       107819
FirstPaymentDate                   78791
ContractEndDate                    76239
Loan_Id                                0
LoanNumber                             0
LoanDate                               0
Gender                                 0
Country                                0
AppliedAmount                          0
Age                                    0
Interest                               0
LoanDuration                           0
MonthlyPayment                         0
Education                              0
EmploymentStatus                       0
OccupationArea                         0
IncomeTotal                            0
Amount                                 0
DebtToIncome                           0
ExpectedLoss                           0
ExpectedReturn                         0
ProbabilityOfDefault                   0
Rating                                 0
Status                                 0
PrincipalPaymentsMade                  0
InterestAndPenaltyPaymentsMade         0
PrincipalBalance                       0
DefaultFlag                            0
OutstandingAmount                      0
RepaymentPercentage                    0
TotalRecived                           0
LoanAgeDays                            0
NetROI                                 0
RiskCategory                           0
dtype: int64

In [54]:
df["NetROI"].isna().sum()

np.int64(0)

In [55]:
df["NetROI"].dtype

dtype('float64')

In [56]:
df.to_csv(
    r"C:\Users\Omkar Kurane\OneDrive\Data_Analytics\Bondara_Project\bondora_sql.csv",
    index=False
)

In [59]:
A=df["NetROI"].isna().sum()
B= df["NetROI"].dtype
print(A,B)

0 float64

In [60]:
df.shape

(179235, 34)

In [62]:
!pip install sqlalchemy pyodbc

Requirement already satisfied: sqlalchemy in c:\python\lib\site-packages (2.0.39)
Requirement already satisfied: pyodbc in c:\python\lib\site-packages (5.2.0)
Requirement already satisfied: greenlet!=0.4.17 in c:\python\lib\site-packages (from sqlalchemy) (3.1.1)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\python\lib\site-packages (from sqlalchemy) (4.12.2)

In [63]:
import pyodbc

print(pyodbc.drivers())

['SQL Server', 'ODBC Driver 17 for SQL Server', 'ODBC Driver 18 for SQL Server', 'Microsoft Access Driver (*.mdb, *.accdb)', 'Microsoft Excel Driver (*.xls, *.xlsx, *.xlsm, *.xlsb)', 'Microsoft Access Text Driver (*.txt, *.csv)', 'Microsoft Access dBASE Driver (*.dbf, *.ndx, *.mdx)']

In [65]:
import pyodbc

conn = pyodbc.connect(
    "DRIVER={ODBC Driver 18 for SQL Server};"
    "SERVER=LAPTOP-7FJ3KQ2\SQLEXPRESS;"
    "DATABASE=Bondora_Project;"
    "Trusted_Connection=yes;"
    "TrustServerCertificate=yes;"
)

print("Connected Successfully!")

Connected Successfully!

In [66]:
from sqlalchemy import create_engine
import urllib

connection_string = (
    "DRIVER={ODBC Driver 18 for SQL Server};"
    "SERVER=YOUR_SERVER_NAME;"
    "DATABASE=Bondora_Project;"
    "Trusted_Connection=yes;"
    "TrustServerCertificate=yes;"
)

params = urllib.parse.quote_plus(connection_string)

engine = create_engine(f"mssql+pyodbc:///?odbc_connect={params}")

print("Engine Created Successfully!")

Engine Created Successfully!

In [67]:
import pandas as pd

df = pd.read_csv(
    r"C:\Users\Omkar Kurane\OneDrive\Data_Analytics\Bondara_Project\bondora_sql.csv"
)

df.to_sql(
    name="bondora_loans",
    con=engine,
    if_exists="replace",   # Creates a new table (or replaces if it already exists)
    index=False,
    chunksize=5000,
    method="multi"
)

print("Data Imported Successfully!")

OperationalError: (pyodbc.OperationalError) ('08001', '[08001] [Microsoft][ODBC Driver 18 for SQL Server]Named Pipes Provider: Could not open a connection to SQL Server [53].  (53) (SQLDriverConnect); [08001] [Microsoft][ODBC Driver 18 for SQL Server]Login timeout expired (0); [08001] [Microsoft][ODBC Driver 18 for SQL Server]A network-related or instance-specific error has occurred while establishing a connection to YOUR_SERVER_NAME. Server is not found or not accessible. Check if instance name is correct and if SQL Server is configured to allow remote connections. For more information see SQL Server Books Online. (53)')
(Background on this error at: https://sqlalche.me/e/20/e3q8)

In [68]:
from sqlalchemy import create_engine
import urllib

connection_string = (
    "DRIVER={ODBC Driver 18 for SQL Server};"
    "SERVER=LAPTOP-7FJ3KQ2\SQLEXPRESS;"
    "DATABASE=Bondora_Project;"
    "Trusted_Connection=yes;"
    "TrustServerCertificate=yes;"
)

params = urllib.parse.quote_plus(connection_string)

engine = create_engine(f"mssql+pyodbc:///?odbc_connect={params}")

print("Engine Created Successfully!")

Engine Created Successfully!

In [69]:
df.to_sql(
    name="bondora_loans",
    con=engine,
    if_exists="replace",
    index=False,
    chunksize=5000
)

print("Data Imported Successfully!")

C:\Python\Lib\site-packages\pandas\io\sql.py:1636: SAWarning: Unrecognized server version info '17.0.1000.7'.  Some SQL Server features may not function properly.
  con = self.exit_stack.enter_context(con.connect())

Data Imported Successfully!